name: {{cookiecutter.project_slug}}
channels:
  - conda
  - conda-forge
  - defaults
dependencies:
  - python={{cookiecutter.python_version}}
  {% if cookiecutter.project_packages == "jupyter" -%}
  - jupyter
  {% endif -%}
  {% if cookiecutter.project_packages == "all" -%}
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  {% endif -%}