name: {{cookiecutter.project_slug}}-env
channels:
  - conda
  - conda-forge
  - defaults
dependencies:
  - python={{cookiecutter.python_version}}
  - pip
  {% if cookiecutter.project_packages == "yes" -%}
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  {% endif -%}
  - pip:
    {% if cookiecutter.project_packages == "yes" -%}
    - pyhere
    {% endif -%}
